<a href="https://colab.research.google.com/github/dogukartal/IBM_AI_Labs/blob/main/Introduction%20to%20Neural%20Networks%20and%20PyTorch/Linear%20Regression/Prediction_1D_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Regression 1D: Prediction
---

<h2 id="Prediction">Prediction</h2>


In [ ]:
import torch

def forward(x):
    yhat = w * x + b
    return yhat

w = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(-1.0, requires_grad = True)

In [ ]:
x = torch.tensor([[1.0]])
yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.]], grad_fn=<AddBackward0>)


In [ ]:
x = torch.tensor([[1.0], [2.0]])
print("The shape of x: ", x.shape)

yhat = forward(x)
print("The prediction: ", yhat)

The shape of x:  torch.Size([2, 1])
The prediction:  tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


<h2 id="Linear">Class Linear</h2>


In [ ]:
from torch.nn import Linear

lr = Linear(in_features=1, out_features=1, bias=True)
print("Parameters w and b: ", list(lr.parameters()))

Parameters w and b:  [Parameter containing:
tensor([[-0.8158]], requires_grad=True), Parameter containing:
tensor([-0.7671], requires_grad=True)]


In [ ]:
print("Python dictionary: ",lr.state_dict())
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())

Python dictionary:  OrderedDict([('weight', tensor([[-0.8158]])), ('bias', tensor([-0.7671]))])
keys:  odict_keys(['weight', 'bias'])
values:  odict_values([tensor([[-0.8158]]), tensor([-0.7671])])


In [ ]:
print("weight:",lr.weight)
print("bias:",lr.bias)

weight: Parameter containing:
tensor([[-0.8158]], requires_grad=True)
bias: Parameter containing:
tensor([-0.7671], requires_grad=True)


In [ ]:
x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[-1.5829]], grad_fn=<AddmmBackward0>)


In [ ]:
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[-1.5829],
        [-2.3988]], grad_fn=<AddmmBackward0>)


<h2 id="Cust">Build Custom Modules</h2>


In [ ]:
from torch import nn

class LR(nn.Module):

    def __init__(self, input_size, output_size):
        # Inherit from parent
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)

    def forward(self, x):
        out = self.linear(x)
        return out

In [ ]:
lr = LR(1, 1)
print("The parameters: ", list(lr.parameters()))
print("Linear model: ", lr.linear)

The parameters:  [Parameter containing:
tensor([[-0.4934]], requires_grad=True), Parameter containing:
tensor([-0.1549], requires_grad=True)]
Linear model:  Linear(in_features=1, out_features=1, bias=True)


In [ ]:
x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[-0.6484]], grad_fn=<AddmmBackward0>)


In [ ]:
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[-0.6484],
        [-1.1418]], grad_fn=<AddmmBackward0>)


In [ ]:
print("Python dictionary: ", lr.state_dict())
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())

Python dictionary:  OrderedDict([('linear.weight', tensor([[-0.4934]])), ('linear.bias', tensor([-0.1549]))])
keys:  odict_keys(['linear.weight', 'linear.bias'])
values:  odict_values([tensor([[-0.4934]]), tensor([-0.1549])])
